#
# CODENVY CONFIDENTIAL
# __________________
#
#  [2012] - [2015] Codenvy, S.A.
#  All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Codenvy S.A. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to Codenvy S.A.
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from Codenvy S.A..
#

installation-manager.download_dir=${HOME}/codenvy-im-data/updates
installation-manager.backup_dir=${HOME}/codenvy-im-data/backups
installation-manager.storage_dir=${HOME}/codenvy-im-data/storage
installation-manager.report_dir=${HOME}/codenvy-im-data/reports
installation-manager.update_server_endpoint=https://codenvy.com/update

puppet.base_dir=/etc/puppet

api.endpoint=http://localhost/api
saas.api.endpoint=https://codenvy.com/api

os.redhat_release_file=/etc/redhat-release
