box      = 'centos7.1-preconfigured.v8.3.box'
url      = 'https://install.codenvycorp.com/centos7.1-preconfigured.v8.3.box'

ram = '6072'
node_ram = '1512' # should be > 1GB
cpus     = '2'

Vagrant.configure("2") do |config|
config.vm.box = box
config.ssh.insert_key = false
config.vm.box_url = url

###################
# PUPPET MASTER INSTANCE
###################
config.vm.define :master do |master_instance_config|
hostname = 'master'
domain = 'codenvy'
master_instance_config.vm.host_name = hostname + '.' + domain
master_instance_config.vm.network :private_network, ip: "192.168.56.110"
master_instance_config.vm.network "forwarded_port", guest: 5005, host: 5005

master_instance_config.vm.provider :virtualbox do |vbox|
vbox.customize [
'modifyvm', :id,
'--name', hostname,
'--memory', ram,
'--cpus', cpus
]
end
end

###################
# NODE 1 INSTANCE
###################
config.vm.define :node1 do |node1_instance_config|
hostname = 'node1'
domain = 'codenvy'
node1_instance_config.vm.host_name = hostname + '.' + domain
node1_instance_config.vm.network :private_network, ip: "192.168.56.15"
node1_instance_config.vm.provider :virtualbox do |vbox|
vbox.customize [
'modifyvm', :id,
'--name', hostname,
'--memory', node_ram,
'--cpus', cpus
]
end
end

###################
# NODE 2 INSTANCE
###################
config.vm.define :node2 do |node2_instance_config|
hostname = 'node2'
domain = 'codenvy'
node2_instance_config.vm.host_name = hostname + '.' + domain
node2_instance_config.vm.network :private_network, ip: "192.168.56.20"
node2_instance_config.vm.provider :virtualbox do |vbox|
vbox.customize [
'modifyvm', :id,
'--name', hostname,
'--memory', node_ram,
'--cpus', cpus
]
end
end

##################
# HOSTS RULES
##################
config.vm.provision "shell", inline: "echo -e \"nameserver 8.8.8.8\n\" >> /etc/resolv.conf"
config.vm.provision :hosts do |config|
config.add_host '192.168.56.15', ['node1.codenvy']
config.add_host '192.168.56.20', ['node2.codenvy']
config.add_host '192.168.56.110', ['codenvy']
end

end
