box      = 'centos7.0-preconfigured.v6'
url      = 'https://install.codenvycorp.com/centos7.0-preconfigured.v6.box'
ram      = '3072'
cpus     = '2'
bridge   = 'eth0'

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.box_url = url
  config.vm.network :private_network, ip: "192.168.56.110"

config.vm.provider :virtualbox do |vbox|
    vbox.customize [
        'modifyvm', :id,
        '--memory', ram,
        '--cpus', cpus
    ]
 end
end
