box      = 'centos7.1-preconfigured.v8.3.box'
url      = 'https://install.codenvycorp.com/centos7.1-preconfigured.v8.3.box'
ram      = '3072'
cpus     = '2'
bridge   = 'eth0'

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.box_url = url
  config.ssh.insert_key = false
  config.vm.network :private_network, ip: "192.168.56.110"
  config.vm.network "forwarded_port", guest: 5005, host: 5005

  config.vm.provider :virtualbox do |vbox|
    vbox.customize [
        'modifyvm', :id,
        '--memory', ram,
        '--cpus', cpus
    ]
  end

  #Adding hosts rules
  config.vm.provision "shell", inline: "echo -e \"127.0.0.1 localhost\" > /etc/hosts"
  config.vm.provision "shell", inline: "echo -e \"nameserver 8.8.8.8\n\" >> /etc/resolv.conf"
end
