box      = 'centos7.1-preconfigured.v8.2.box'
url      = 'https://install.codenvycorp.com/centos7.1-preconfigured.v8.2.box'
ram      = '3072'
cpus     = '2'
bridge   = 'eth0'

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.box_url = url
  config.vm.network :private_network, ip: "192.168.56.110"
  config.vm.network "forwarded_port", guest: 9000, host: 9000

config.vm.provider :virtualbox do |vbox|
    vbox.customize [
        'modifyvm', :id,
        '--memory', ram,
        '--cpus', cpus
    ]
 end
end
